---
- hosts: BACKBONE
  connection: local
  gather_facts: no

  tasks:
  - name: save running-config
    ios_config:
      provider:
        timeout: 60
      save_when: modified
#      timeout: 30 ==> Deprecated !!!
